apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: task-service-account
  name: task-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: task-server-role-binding-hanjl
  labels:
    app: task-server-role-binding-hanjl
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: task-service-account
  namespace: hanjl
