apiVersion: v1
kind: Service
metadata:
  name: svc-ssh-task-v0
  namespace: hanjl
spec:
  allocateLoadBalancerNodePorts: false
  type: LoadBalancer
  # loadBalancerIP: 192.168.4.10
  externalIPs:
  - 192.168.4.10
  selector:
    k8s-ssh-task-server: v0
  ports:
  - name: ssh
    port: 9376
    targetPort: 22