apiVersion: v1
kind: Service
metadata:
  name: svc-gateway-v0
spec:
  allocateLoadBalancerNodePorts: false
  type: LoadBalancer
  # loadBalancerIP: 192.168.4.10
  externalIPs:
  - 192.168.4.10
  selector:
    k8s-gateway-server: v0
  ports:
  - name: gateway
    port: 10002
    targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-gateway-server-v0
  namespace: hanjl
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-gateway-server: v0
      k8s-ssh-gateway-server: v0
  template:
    metadata:
      labels:
        k8s-gateway-server: v0
        k8s-ssh-gateway-server: v0
    spec:
      containers:
      - name: k8s-gateway-server
        image: docker.kt.io/rlg1/hanjl/going:v1
        command: ["/bin/bash","-c"]
        args:
        - service ssh restart;while true;do sleep 10h;done
        volumeMounts:
        - mountPath: /data/hanjl
          name: storage
      volumes:
      - name: storage
        nfs:
          server: 169.252.198.3
          path: /NAS_DATA/NAS_DATA/hanjl
      nodeName: by10
