apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: quota-service-account
  name: quota-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: quota-server-role-binding-lzm
  labels:
    app: quota-server-role-binding-lzm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: quota-service-account
  namespace: lzm
