apiVersion: v1
kind: Service
metadata:
  name: k8s-mysql
spec:
  ports:
  - name: k8s-mysql
    port: 40003
    targetPort: 3306
  selector:
    app: k8s-mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-mysql
  namespace: hanjl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-mysql
  template:
    metadata:
      labels: 
        app: k8s-mysql
    spec:
      containers:
      - name: mysql
        image: hanjl/mysql:v0
        command: ["/bin/bash","-c"]
        args:
        - chown -R mysql:mysql /var/lib/mysql;usermod -d /var/lib/mysql/ mysql;service mysql restart;while true;do sleep 10h;done
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-storage
      volumes:
      - name: mysql-storage
        nfs:
          server: 169.252.198.3
          path: /NAS_DATA/NAS_DATA/k8s-storage/mysql
