apiVersion: v1
kind: Service
metadata:
  name: test-mysql
spec:
  ports:
  - name: test-mysql
    port: 40005
    targetPort: 3306
  selector:
    app: test-mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-mysql
  namespace: hanjl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-mysql
  template:
    metadata:
      labels: 
        app: test-mysql
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
      - name: mysql
        image: hanjl/mysql:v0
        command: ["/bin/bash","-c"]
        args:
        - chown -R mysql:mysql /var/lib/mysql;usermod -d /var/lib/mysql/ mysql;service mysql restart;while true;do sleep 10h;done
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: task-pv-storage
      nodeName: by10
