apiVersion: v1
kind: Service
metadata:
  name: svc-user-v0
  namespace: hanjl
spec:
  selector:
    k8s-user-server: v0
  ports:
    - name: user
      port: 8001
      targetPort: 8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-user-server-v0
  namespace: hanjl
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-user-server: v0
      k8s-ssh-user-server: v0
  template:
    metadata:
      labels:
        k8s-user-server: v0
        k8s-ssh-user-server: v0
    spec:
      serviceAccountName: user-service-account
      containers:
      - name: k8s-user-server
        image: docker.kt.io/rlg1/hanjl/going:v1
        command: ["/bin/bash","-c"]
        args:
        - service ssh restart;while true;do sleep 10h;done
        volumeMounts:
        - mountPath: /data/hanjl
          name: storage
      volumes:
      - name: storage
        nfs:
          server: 169.252.198.3
          path: /NAS_DATA/NAS_DATA/hanjl
      nodeName: by10
